name: "Build&Deploy ros-buildtools images"

on:
  # Trigger the workflow on push or pull request
  # but only for the main branch
  # or on tag of type v*.*.*
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  release:
    types: [released]
jobs:
  ros-buildtools-melodic:
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@v1
    with:
      docker_file: melodic/Dockerfile
      docker_image: qa/ros-buildtools-melodic
      docker_registry: registry.aws.cloud.mov.ai
      github_ref: ${{ github.ref }}
      deploy: ${{ contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/tags/v')}}
      version: ${GITHUB_REF##*/}
      push_latest: ${{ contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/tags/v') }}
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      pub_registry_user: ${{ secrets.PORTUS_APP_USER }}
      pub_registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      snyk_token: ${{ secrets.SNYK_TOKEN }}


  ros-buildtools-noetic:
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@v1
    with:
      docker_file: noetic/Dockerfile
      docker_image: qa/ros-buildtools-noetic
      docker_registry: registry.aws.cloud.mov.ai
      github_ref: ${{ github.ref }}
      deploy: ${{ contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/tags/v')}}
      version: ${GITHUB_REF##*/}
      push_latest: ${{ contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/tags/v') }}

    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      pub_registry_user: ${{ secrets.PORTUS_APP_USER }}
      pub_registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      snyk_token: ${{ secrets.SNYK_TOKEN }}